# Site settings
author: Yukiji Nakatsuka
title: 
header-img: img/home-bg.png
email: lunarbase@outlook.com
copyright_name: Yukiji Nakatsuka
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  yukijina

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
